### ISSUE TITLE
Show friend's logo while browsing list of friends

### ISSUE THREAD

**Issue by JoKeRzBoX** [ddurdle/KODI-Hive#13]
Nice to have. I've sent a pull request proposing a code change to show the logos. 

Cheers!

JoKeRz BoX

**Comment by ddurdle** [comment]
I removed the unused playbackType and isQuickLink.  I also did some slight refactoring.  None of the changes are functional changes.  If you make any changes, I'll merge them.

I pushed the refactoring to the master but I'm not pushing a release since there is no functional changes.
