### ISSUE TITLE
With 0.2.4 version in my kodi (RPi) I can not play anything

### ISSUE THREAD

**Issue by tranqui69** [ddurdle/KODI-Hive#17]
With 2 premium accounts.
Thanks for the job anyway.

**Comment by ddurdle** [comment]
Don't fret. Give 0.2.5 a try.

Made a change and it should be working now. I don't have a second account to test, but from what I see, the issue should be fixed.

I'll be creating a second account via the Google Login, to try to get Google Login support going.

http://dmdsoftware.net/repository.ddurdle/plugin.video.hive-0.2.5.zip
Version 0.2.5
- fix: playing back when using multiple accounts
- nekwebdev contribution: saving movies and tv shows to "easily" XBMC importable folders -- enhancements
- nekwebdev contribution: Integration with thetvdb #5 -- enhancements

**Comment by ddurdle** [comment]
Looks like confirmation in forum that fix works.  closing
